### ISSUE TITLE
how to generate density_maps_constant15 for vis

### ISSUE THREAD

**Issue by zhou-rui1** [wfs123456/CCTrans#6]
Hi, I am wondering about  how to create this file in the vis_densityMap process:

https://github.com/wfs123456/CCTrans/blob/58c8d0c257774bfd37b64cafbf265e5def344466/vis_densityMap.py#L77

gt_dmap_path = image_path.replace('.jpg', '.npy').replace('images', 'density_maps_constant15')

**Comment by wfs123456** [comment]
Hello! DM-Count-loss&nbsp; only needs dot-map as ground truth. In vis_density-map.py，the ---constant15 is the density-map generated by&nbsp;Gaussian smoothing，referencing paper MCNN/CSRNet，and the constant15 is only used to compare the output of CCTrans. So, you can also delete this line of code，only print and visualize the output of CCTrans.



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 4, 2022 23:09 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [wfs123456/CCTrans] how to generate density_maps_constant15 for vis (Issue #6)




 
Hi, I am wondering about  how to create this file in the vis_densityMap process:
 
https://github.com/wfs123456/CCTrans/blob/58c8d0c257774bfd37b64cafbf265e5def344466/vis_densityMap.py#L77
 
gt_dmap_path = image_path.replace('.jpg', '.npy').replace('images', 'density_maps_constant15')

**Comment by zhou-rui1** [comment]
Thanks a lot! It goes well now.

**Comment by zhou-rui1** [comment]
Hi, have you try the code on NWPU dataset? the validated mae seems to remain high(over 300) and it is hard to train lower, I am wondering if this is due to some problem in the preprocess_dataset_nwpu.py?

**Comment by wfs123456** [comment]
For NWPU dataset，i reshaped the resolution of all images to avoid out of memory of gpu. The preprocess_dataset_nwpu.py has been changed, that might have been handled incorrectly because of time. (please refer to the DM-Count code or directly adopt original resolution for training in NWPU if the gpu is enough!

---Original---
From: ***@***.***&gt;
Date: Sat, Apr 9, 2022 00:05 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wfs123456/CCTrans] how to generate density_maps_constant15 forvis (Issue #6)




 
Hi, have you try the code on NWPU dataset? the validated mae seems to remain high(over 300) and it is hard to train lower, I am wondering if this is due to some problem in the preprocess_dataset_nwpu.py?
